### ISSUE TITLE
Unexpected 401 error for logged in users

### ISSUE THREAD

**Issue by s312121** [filippoCaste/se2-05-ThesisManagement#17]
It seems that there is a bug in the login and authentication section. Immediately after logging in with the student account, no proposal is shown on the proposal search page, and this is because the corresponding API gives a 401 error.

![401 error](https://github.com/filippoCaste/se2-05-ThesisManagement/assets/135665531/be8b0cd2-7f7a-468f-aae2-cb0ffa8fd956)

**Comment by filippoCaste** [comment]
solved
