### ISSUE TITLE
TeacherPage must be correct

### ISSUE THREAD

**Issue by GioGiunta2606** [filippoCaste/se2-05-ThesisManagement#21]
At the moment the filter between posted and archived is not managed as we want. 

In this sprint we have to do story "TM-12 archive proposal" so a story is archived when a professor clicks on the archive button.

In the next sprint maybe we will have also to do story "TM-15 proposal expiration" in which a proposal is archived also if the current date is after the expiration date of the proposal.

Probably for this sprint, according to the story we committed, is better to don't use virtualClock on the teacher side and consider a story archived only if the professor clicks on the archive button (according to story TM-12).

In the next sprint when we will implement also story TM-15 we will use virtual clock

**Comment by Frirhos-he** [comment]
Done in the notify branch
